# Generated by Django 5.0.6 on 2024-05-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_color_tag_tag_type_alter_image_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag type',
            new_name='color',
        ),
    ]
