# Generated by Django 5.0.6 on 2024-05-17 18:14

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_tag_type_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=gallery.models.update_filename),
        ),
    ]
