# Generated by Django 5.0.6 on 2024-05-17 21:13

import django.core.validators
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_image_file_alter_image_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(max_length=255, upload_to=gallery.models.update_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'avif', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'gif', 'webp', 'apng', 'svg', 'mp4', 'webm'])]),
        ),
    ]
