# Generated by Django 5.0.6 on 2024-05-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='id',
            new_name='iid',
        ),
    ]
