# Generated by Django 5.0.6 on 2024-05-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_rename_id_image_iid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='iid',
            new_name='id',
        ),
    ]
