# Generated by Django 5.0.6 on 2024-05-18 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_rename_iid_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(max_length=255, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'avif', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'gif', 'webp', 'apng', 'svg', 'mp4', 'webm'])]),
        ),
    ]
