# Generated by Django 5.0.6 on 2024-05-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
