# Generated by Django 5.0.6 on 2024-05-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_alter_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.FilePathField(editable=False, null=True, path='/mnt/c/Users/perso/OneDrive/Documents/dijango/boorish/boorish/gallery/images'),
        ),
    ]
