# Generated by Django 5.0.6 on 2024-05-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_alter_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
    ]
