# Generated by Django 5.0.6 on 2024-05-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_remove_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
