# Generated by Django 5.0.6 on 2024-05-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_image_is_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_video',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
