# Generated by Django 5.0.6 on 2024-05-22 20:04

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_alter_image_is_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=300, validators=[gallery.models.validate_no_comma]),
        ),
    ]
