# Generated by Django 5.0.6 on 2024-05-22 21:02

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[gallery.models.validate_no_comma]),
        ),
    ]
