# Generated by Django 5.0.6 on 2024-06-07 00:17

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_animated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[gallery.models.validate_no_comma, gallery.models.validate_no_leading_trailing_spaces]),
        ),
    ]
